spring.application.name=CarPoolingApplication-SATHI
#configuring database
spring.datasource.url = jdbc:mysql://localhost:3306/carpoolingapplication_sathi
spring.datasource.username = root
spring.datasource.password = root
#configuring hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
#Logging
logging.level.org.springframework = INFO
logging.level.org.hibernate = INFO
#Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
# local properties enable
spring.profiles.active=local